"""Add geospatial fields to Farm

Revision ID: 7e127ce706b7
Revises: 
Create Date: 2026-05-10 10:40:00.765879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e127ce706b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('analysis_radius', sa.Float(), nullable=True))
    op.add_column('farms', sa.Column('boundary_polygon', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'boundary_polygon')
    op.drop_column('farms', 'analysis_radius')
    # ### end Alembic commands ###
