"""Create all initial tables

Revision ID: 7e127ce706b7
Revises: 
Create Date: 2026-05-10 10:40:00.765879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e127ce706b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('farm_name', sa.String(length=255), nullable=False),
        sa.Column('location_name', sa.String(length=255), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('farm_size', sa.Float(), nullable=True),
        sa.Column('soil_type', sa.String(length=100), nullable=True),
        sa.Column('analysis_radius', sa.Float(), nullable=True),
        sa.Column('boundary_polygon', sa.JSON(), nullable=True),
        sa.Column('irrigation_method', sa.String(length=50), nullable=True),
        sa.Column('water_availability', sa.Float(), nullable=True),
        sa.Column('active_crop', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_farm_name'), 'farms', ['farm_name'], unique=False)
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    
    op.create_table('weather_data',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('farm_id', sa.Uuid(), nullable=False),
        sa.Column('temperature', sa.Float(), nullable=False),
        sa.Column('humidity', sa.Float(), nullable=False),
        sa.Column('rainfall', sa.Float(), nullable=False),
        sa.Column('wind_speed', sa.Float(), nullable=False),
        sa.Column('pressure', sa.Float(), nullable=False),
        sa.Column('weather_condition', sa.String(length=100), nullable=True),
        sa.Column('recorded_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_data_farm_id'), 'weather_data', ['farm_id'], unique=False)
    op.create_index(op.f('ix_weather_data_recorded_at'), 'weather_data', ['recorded_at'], unique=False)
    op.create_index('idx_weather_farm_recorded', 'weather_data', ['farm_id', 'recorded_at'], unique=False)
    
    op.create_table('soil_data',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('farm_id', sa.Uuid(), nullable=False),
        sa.Column('soil_moisture', sa.Float(), nullable=False),
        sa.Column('soil_temperature', sa.Float(), nullable=False),
        sa.Column('nitrogen_level', sa.Float(), nullable=False),
        sa.Column('phosphorus_level', sa.Float(), nullable=False),
        sa.Column('potassium_level', sa.Float(), nullable=False),
        sa.Column('ph_level', sa.Float(), nullable=False),
        sa.Column('recorded_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_data_farm_id'), 'soil_data', ['farm_id'], unique=False)
    op.create_index(op.f('ix_soil_data_recorded_at'), 'soil_data', ['recorded_at'], unique=False)
    op.create_index('idx_soil_farm_recorded', 'soil_data', ['farm_id', 'recorded_at'], unique=False)
    
    op.create_table('environmental_metrics',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('farm_id', sa.Uuid(), nullable=False),
        sa.Column('drought_risk_score', sa.Float(), nullable=True),
        sa.Column('evaporation_index', sa.Float(), nullable=True),
        sa.Column('heat_stress_score', sa.Float(), nullable=True),
        sa.Column('humidity_trend', sa.Float(), nullable=True),
        sa.Column('calculated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_metrics_farm_id'), 'environmental_metrics', ['farm_id'], unique=False)
    op.create_index(op.f('ix_environmental_metrics_calculated_at'), 'environmental_metrics', ['calculated_at'], unique=False)
    op.create_index('idx_env_farm_calculated', 'environmental_metrics', ['farm_id', 'calculated_at'], unique=False)
    
    op.create_table('ai_predictions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('farm_id', sa.Uuid(), nullable=False),
        sa.Column('prediction_type', sa.String(length=100), nullable=False),
        sa.Column('prediction_value', sa.Float(), nullable=False),
        sa.Column('confidence_score', sa.Float(), nullable=False),
        sa.Column('model_version', sa.String(length=50), nullable=False),
        sa.Column('explanation', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_predictions_farm_id'), 'ai_predictions', ['farm_id'], unique=False)
    op.create_index(op.f('ix_ai_predictions_prediction_type'), 'ai_predictions', ['prediction_type'], unique=False)
    
    op.create_table('recommendations',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('farm_id', sa.Uuid(), nullable=False),
        sa.Column('recommendation_type', sa.String(length=100), nullable=False),
        sa.Column('recommendation_text', sa.Text(), nullable=False),
        sa.Column('priority_level', sa.Integer(), nullable=False),
        sa.Column('generated_by', sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_farm_id'), 'recommendations', ['farm_id'], unique=False)
    
    op.create_table('alerts',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('farm_id', sa.Uuid(), nullable=False),
        sa.Column('alert_type', sa.String(length=100), nullable=False),
        sa.Column('alert_message', sa.Text(), nullable=False),
        sa.Column('severity', sa.Integer(), nullable=False),
        sa.Column('is_resolved', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_farm_id'), 'alerts', ['farm_id'], unique=False)
    op.create_index(op.f('ix_alerts_is_resolved'), 'alerts', ['is_resolved'], unique=False)
    
    op.create_table('crop_profiles',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('farm_id', sa.Uuid(), nullable=False),
        sa.Column('crop_name', sa.String(length=100), nullable=False),
        sa.Column('planting_date', sa.DateTime(), nullable=True),
        sa.Column('expected_harvest_date', sa.DateTime(), nullable=True),
        sa.Column('growth_stage', sa.String(length=50), nullable=True),
        sa.Column('irrigation_frequency', sa.Integer(), nullable=True),
        sa.Column('season', sa.String(length=50), nullable=True),
        sa.Column('expected_yield_tons', sa.Float(), nullable=True),
        sa.Column('ai_recommendation_score', sa.Float(), nullable=True),
        sa.Column('recommendation_reasoning', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_profiles_farm_id'), 'crop_profiles', ['farm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_profiles_farm_id'), table_name='crop_profiles')
    op.drop_table('crop_profiles')
    op.drop_index(op.f('ix_alerts_is_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_farm_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_recommendations_farm_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_ai_predictions_prediction_type'), table_name='ai_predictions')
    op.drop_index(op.f('ix_ai_predictions_farm_id'), table_name='ai_predictions')
    op.drop_table('ai_predictions')
    op.drop_index('idx_env_farm_calculated', table_name='environmental_metrics')
    op.drop_index(op.f('ix_environmental_metrics_calculated_at'), table_name='environmental_metrics')
    op.drop_index(op.f('ix_environmental_metrics_farm_id'), table_name='environmental_metrics')
    op.drop_table('environmental_metrics')
    op.drop_index('idx_soil_farm_recorded', table_name='soil_data')
    op.drop_index(op.f('ix_soil_data_recorded_at'), table_name='soil_data')
    op.drop_index(op.f('ix_soil_data_farm_id'), table_name='soil_data')
    op.drop_table('soil_data')
    op.drop_index('idx_weather_farm_recorded', table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_recorded_at'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_farm_id'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_farm_name'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
